### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by tjunno** [mikkokotola/AltitudeRoutes#1]
### Koodi haettu 9.1.2018 klo 17:22

* Ensimmäinen testiajo tervehti seuraavanlaisilla ilmoituksilla:
error: package javafx.application does not exist import javafx.application.Application;
Tämä kuitenkin ilmeisesti johtui vain siitä ettei openjdk:n mukana tule javafx:ää samassa paketissa (eli ongelma ei sinänsä ollut testattavassa projektissa, mutta on ehkä hyvä huomioida ehkä taas ei).

* Ohjelma vaikuttaa edenneen hyvin aikataulussa ja algoritmit kuten myös tietorakenteet vaikuttavat toimivilta.

* Testitkin tuntuvat pitkälti toimivan ja codecovin käyttö tuo selkeytystä niihin. Mitään huomautettavaa ko. luokista ei havaittu.

* Ainakin graph-luokissa vaikutti olevan jonkin verran käyttämättömiä importteja. Noin muuten importeista en tiedä olisiko mielekkäämpää käyttää java.utils.* tyylisiä wildcardeja ja antaisi javan huolehtia tarkemmin vai ei, tämä lienee makuasia.

* Luokkien hieman tarkempi dokumentointi koodissa toisi lisää luettavuutta. Esimerkiksi kannatanee käyttää luokkien metodeissa javadocin tägejä kuten @return tagiä (kun niissä joissakin returnistä muuten kerrotaan).

* Jos onnistuu syöttämään tiedoston mitä ei ole niin voisiko olla hyvä laittaa jokin tarkastus asian tiimoilta jotta voisi syöttää filen oikein ettei softa turhaan yritä lähteä ajamaan kokonaisuutta (tämä koko asia varmasti on työnalla).

* Käyttöliittymästä vain sen verran että se lienee kovasti työnalla, mutta en tiedä onko kannattavaa ns. tehdä kaikki luokkien metodit uudelleen

* Projekti näyttää oikein hyvältä, ei muuta kuin tsemppiä jatkoon

**Comment by mikkokotola** [comment]
Kiitos kommenteista! Käli vielä pohdinnassa. Javadoc-dokumentointia täytyy tosiaan vielä hioa, ei ole vielä tasalaatuista. Hyvää loppusuoraa omaankin projektiisi!
