### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by RoopeNiemi** [mikkokotola/AltitudeRoutes#2]
Ohjelma ladattu 12.01.2018 klo 10.26

Koodi oli yleisesti katsottuna selkeää ja hyvin kommentoitua. Metodit pysyivät lyhyinä ja testien määrä vaikutti hyvältä.

Hakualgoritmeissa huomasin että reitti merkataan löydetyksi jo kun etsittävä solmu löytyy, sen sijaan että tämä tapahtuisi vasta kun solmu lisätään käytyjen solmujen S joukkoon. 

Onko tarkoitus että haun pystyy tekemään vain kerran, jonka jälkeen ohjelma käynnistetään uudestaan? InitialiseSingleSource ei resetoinut etäisyyksiä lähtösolmusta

**Comment by mikkokotola** [comment]
Kiitos huomioista! Tuon haun päättämiskriteeri on tosiaan virheellinen, korjaan sen - suurkiitos bongauksesta! Haut pystyy nytkin suorittamaan useita kertoja, mutta verkon resetointi on tehty Graph-luokassa omana metodinaan ja sen kutsuminen on haun käynnistäjän vastuulla. Ehkä voisi olla oma pointtinsa siirtää tuo resetointi sinne haun sisään. Silloin se tulisi mukaan aikaanalyysin piiriinkin.
